module.exports.config = {
  name: "boysdp",
  version: "1.0.0",
  hasPermssion: 0,
  credits:"ABabu Aryan",
  description: "",
  commandCategory: "random-img",
  usages: "art",
  cooldowns: 5,
  dependencies: {
    "request":"",
    "fs-extra":"",
    "axios":""
  }

};

module.exports.run = async({api,event,args,Users,Threads,Currencies}) => {
const axios = global.nodemodule["axios"];
const request = global.nodemodule["request"];
const fs = global.nodemodule["fs-extra"];
  var link = [
  "https://i.imgur.com/9Fs4YzT.jpeg",
"https://i.imgur.com/WIkVZuj.jpeg",
"https://i.imgur.com/ayq43ma.jpeg",
"https://i.imgur.com/qhHvJgP.jpeg",
"https://i.imgur.com/FvSidNO.jpeg",
"https://i.imgur.com/sWs8nas.jpeg",
"https://i.imgur.com/bSq52BK.jpeg",
"https://i.imgur.com/ULxBzTy.jpeg",
"https://i.imgur.com/YcyZZ0u.jpeg",
"https://i.imgur.com/oqpZTEV.jpeg",
"https://i.imgur.com/lvnzdmz.jpeg",
"https://i.imgur.com/gGg29oU.jpeg",
"https://i.imgur.com/Dkg1zGO.jpeg",
"https://i.imgur.com/QPeuhIb.jpeg",
"https://i.imgur.com/hQq7g3x.jpeg",
"https://i.imgur.com/aBwzCmt.jpeg",
"https://i.imgur.com/hhuCyC0.jpeg",
"https://i.imgur.com/8Yf8fS3.jpeg",
"https://i.imgur.com/Sogn6pN.jpeg",
"https://i.imgur.com/Er2miTi.jpeg",
"https://i.imgur.com/WLPIVki.jpeg",
"https://i.imgur.com/h9S561S.jpeg",
"https://i.imgur.com/VGVOMAo.jpeg",
"https://i.imgur.com/Oj8hpnU.jpeg",
"https://i.imgur.com/VI3NLW5.jpeg",
"https://i.imgur.com/Oxc47dp.jpeg",
"https://i.imgur.com/Yp6ho24.jpeg",
"https://i.imgur.com/yEzSpEp.jpeg",
"https://i.imgur.com/fUaeKnB.jpeg",
"https://i.imgur.com/2hmJgri.jpeg",
"https://i.imgur.com/pB1sjo9.jpeg",
"https://i.imgur.com/Zz9V7TH.jpeg",
"https://i.imgur.com/tSUAcLg.jpeg",
"https://i.imgur.com/kJy7ngg.jpeg",
"https://i.imgur.com/q3pfCnE.jpeg",
"https://i.imgur.com/crZqBpl.jpeg",
"https://i.imgur.com/UUI8I72.jpeg",
"https://i.imgur.com/tAu18eI.jpeg",
"https://i.imgur.com/aYhStTH.jpeg",
"https://i.imgur.com/FzxaAzh.jpeg",
"https://i.imgur.com/epdawCy.jpeg",
"https://i.imgur.com/gn2bATc.jpeg",
"https://i.imgur.com/eHa6x1H.jpeg",
"https://i.imgur.com/dskZStK.jpeg",
"https://i.imgur.com/SkNXdzE.jpeg",
"https://i.imgur.com/uODmUx5.jpeg",
"https://i.imgur.com/5uEYIlY.jpeg",
"https://i.imgur.com/ZPv5Y9h.jpeg",
"https://i.imgur.com/67sJsPp.jpeg",
"https://i.imgur.com/FRDpMGy.jpeg",
"https://i.imgur.com/YqKqaGQ.jpeg",
"https://i.imgur.com/qYiQ2qn.jpeg",
"https://i.imgur.com/3j1r1Eo.jpeg",
"https://i.imgur.com/uufVCz4.jpeg",
"https://i.imgur.com/dxTW19W.jpeg",
"https://i.imgur.com/ywFkcky.jpeg",
"https://i.imgur.com/cfo1pa9.jpeg",
"https://i.imgur.com/jqz8S0Z.jpeg",
"https://i.imgur.com/EuUxszj.jpeg",
"https://i.imgur.com/fAykbAb.jpeg",
"https://i.imgur.com/S8IMTBG.jpeg",
"https://i.imgur.com/si3f1mD.jpeg",
"https://i.imgur.com/hT4noTi.jpeg",
"https://i.imgur.com/T80ynxc.jpeg",
"https://i.imgur.com/9VegL4c.jpeg",
"https://i.imgur.com/r7N8df9.jpeg",
"https://i.imgur.com/SYDMTW1.jpeg",
"https://i.imgur.com/dFRDCd1.jpeg",
"https://i.imgur.com/w80pZd9.jpeg",
"https://i.imgur.com/g4QH1sg.jpeg",
"https://i.imgur.com/lNaDEYi.jpeg",
"https://i.imgur.com/IEO6r3e.jpeg",
"https://i.imgur.com/weUgDxY.jpeg",
"https://i.imgur.com/Yqz4iIY.jpeg",
"https://i.imgur.com/Ygd6D6u.jpeg",
"https://i.imgur.com/73O6YWJ.jpeg",
"https://i.imgur.com/JB6od9I.jpeg",
"https://i.imgur.com/lVjB9Lq.jpeg",
"https://i.imgur.com/dVhGeAI.jpeg",
"https://i.imgur.com/2CfXltf.jpeg",
"https://i.imgur.com/rFskfEu.jpeg",
"https://i.imgur.com/EBwneLI.jpeg",
"https://i.imgur.com/JKPqF39.jpeg",
"https://i.imgur.com/Q00Q9zL.jpeg",
"https://i.imgur.com/fOSrd6s.jpeg",
"https://i.imgur.com/NGiVmU3.jpeg",
"https://i.imgur.com/LQMuNku.jpeg",
"https://i.imgur.com/dhkaImy.jpeg",
"https://i.imgur.com/PTCKWPw.jpeg",
"https://i.imgur.com/wCmKqgq.jpeg",
"https://i.imgur.com/DiZPgYA.jpeg",
"https://i.imgur.com/jjcGhOc.jpeg",
"https://i.imgur.com/SBMrrWz.jpeg",
"https://i.imgur.com/ncapCkK.jpeg",
"https://i.imgur.com/FWO8Fx9.jpeg",
"https://i.imgur.com/qf8F5lr.jpeg",
"https://i.imgur.com/rQEgXW4.jpeg",
"https://i.imgur.com/s6OIpyX.jpeg",
"https://i.imgur.com/Fj6Hyd6.jpeg",
"https://i.imgur.com/9zzDdyV.jpeg",
"https://i.imgur.com/q7LET4V.jpeg",
"https://i.imgur.com/udAzwXs.jpeg",
"https://i.imgur.com/EjI4rLq.jpeg",
"https://i.imgur.com/lGZMaAV.jpeg",
"https://i.imgur.com/IhG3veJ.jpeg",
"https://i.imgur.com/2droHD6.jpeg",
"https://i.imgur.com/TJhx1Xo.jpeg",
"https://i.imgur.com/9Bh5Gh3.jpeg",

  ];
  var max = Math.floor(Math.random() * 6);  
var min = Math.floor(Math.random() * 2);
  var data = await Currencies.getData(event.senderID);
  var exp =  data.exp;
  var money = data.money
      if(money < 0) api.sendMessage("You need 100 dollars to see the photo ?",event.threadID,event.messageID)
          else {
   Currencies.setData(event.senderID, options = {money: money - 0})
   var callback = () => api.sendMessage({body:`𝓣𝓱𝓲𝓼 𝓟𝓱𝓸𝓽𝓸 𝓒𝓸𝓶𝓶𝓪𝓷𝓭𝓼 𝓶𝓪𝓭𝓮 𝓫𝔂 𝓐𝓻𝔂𝓪𝓷 𝓑𝓪𝓫𝓾\n\n- ❤️🍫`,attachment: fs.createReadStream(__dirname + "/cache/1.jpg")}, event.threadID, () => fs.unlinkSync(__dirname + "/cache/1.jpg"), event.messageID); 
      return request(encodeURI(link[Math.floor(Math.random() * link.length)] + (max - min))).pipe(fs.createWriteStream(__dirname+"/cache/1.jpg")).on("close",() => callback());
     }
   };
